#!/bin/sh
if [ $# -lt 1 ]; then
	echo "Usage: $0 [-f] <major | minor | patch | premajor | preminor | prepatch | prerelease | alpha | beta>"
	exit
fi
FORCE=0
if [ "$1" = "-f" ]; then
	FORCE=1
	shift
fi

DIRTY=$(git status --untracked-files=no --porcelain)
if [ -n "${DIRTY}" ]; then
	echo -e "\033[33mERROR: Working directory is not clean\033[m"
	exit
fi

date=$(date +%Y%m%d)
PREID=""
CMD="$1"
if [ "${CMD}" = "alpha" -o "${CMD}" = "beta" ]; then
	PREID="${CMD}"
	CMD="prerelease"
fi

updated=""
last_release_tag=$(git tag|grep release|sort -r|head -1)
for d in packages/*; do
	echo -n "${d}: "
	changes=$(git log --oneline ${last_release_tag}.. $d | wc -l)

	if [ ${changes} -gt 0 -o ${FORCE} -gt 0 ]; then
		echo "${changes} changes."
		version=$(cd $d; npm version --no-git-tag-version --preid="${PREID}" "${CMD}")
		updated="${updated}|$(cd $d; jq -rc '.name + ": " + .version' package.json)"
	else
		echo "None"
	fi
done

msg=$(echo -e "release: $date\n$updated" | sed 's/|/\n  /g')

git commit -m "$msg" -a
git tag release-${date}
